### PR TITLE
Add small msg to the README

### PR DESCRIPTION
**Pull request by traycycles**
Hey guys, I was just testing this part out from a Treehouse tutorial.  Using the method I just did will allow us to leave messages for one another as well as for us to remember why we did what we did.  For you to review... We can use "Team mentions" so that everyone will see your message. Feel free to try it yourself. Kinda like slack...
@tt-n-friends/developers

### CODE REVIEW

**Comment by JonBrouQ22** [comment]
Only you can merge this into the master at the moment.

**Comment by traycycles** [comment]
try adding your own pull request. you will go to the readme commit and edit the file using the online editor. create your pull request with a message to us.

**Comment by traycycles** [comment]
updated readme is a branch

**Comment by traycycles** [comment]
Did you make your own pull request on it?

**Pull request merged**
